### ISSUE TITLE
Correct `pyproject.toml` build-backend specification

### ISSUE THREAD

**Issue by nikitos3000** [matze/pkgconfig#51]
According to https://python-poetry.org/docs/pyproject/#poetry-and-pep-517

> If your `pyproject.toml` file still references poetry directly as a build backend, you should update it to reference poetry_core instead.

Should be updated  to,

```toml
[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

This will significantly speed up the package installation process, since the entire `poetry` dependency cone is currently being installed during isolated build per PEP517.

I can submit a PR if no objections.
